In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

handshake_df = pd.read_csv("./handshake.csv")
display(
    handshake_df.groupby(["kex", "auth"]).size(
    ).reset_index(name="count").sort_values(["kex", "auth"])
)

          kex                                 auth  count
0      hqc128       sphincs128s-sphincs128s-hqc128   3340
1      hqc128  sphincs128s-sphincs128s-sphincs128s   3568
2      hqc192       sphincs192s-sphincs192s-hqc192   1302
3      hqc192      sphincs192s-sphincs192s-mldsa65   1236
4      hqc256       sphincs256s-sphincs256s-hqc256   1096
5      hqc256      sphincs256s-sphincs256s-mldsa87   1209
6   mlkem1024      falcon1024-falcon1024-mlkem1024   1530
7   mlkem1024            mldsa87-mldsa87-mlkem1024   1719
8   mlkem1024    sphincs256s-sphincs256s-mlkem1024   1029
9    mlkem512         falcon512-falcon512-mlkem512   1071
10   mlkem512              mldsa44-mldsa44-mldsa44    104
11   mlkem512             mldsa44-mldsa44-mlkem512    102
12   mlkem512     sphincs128s-sphincs128s-mlkem512   1087
13   mlkem768       falcon1024-falcon1024-mlkem768   1310
14   mlkem768             mldsa65-mldsa65-mlkem768   1445
15   mlkem768             mldsa87-mldsa87-mlkem768   1666
16   mlkem768     sphincs192s-sphincs192s-mlkem768   1176
17  secp256r1              rsa2048-rsa2048-rsa2048   2234
18  secp256r1  sha256ecdsa-sha256ecdsa-sha256ecdsa    100

In [6]:
def plot_multiple_histograms(data_dict, bins=10, alpha=0.6, title=None, 
                             density=True, save=None, figsize=(15, 6)):
    """
    Plots multiple histograms on the same figure for each label in the input dictionary.

    Parameters:
        data_dict (dict): A dictionary where keys are labels (str) and values are lists of integers.
        bins (int): Number of bins to use in the histograms.
        alpha (float): Transparency level for the histograms (0.0 to 1.0).
        title (str): Title of the plot.
    """
    plt.figure(figsize=figsize)

    for label, values in data_dict.items():
        weights = (np.ones_like(values) / len(values)) * 100
        plt.hist(values, bins=bins, alpha=alpha, label=label, weights=weights)

    plt.title(title)
    plt.xlabel("Duration (microseconds)")
    plt.ylabel("Percentage" if density else "Count")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    if save:
        plt.savefig(save, dpi=300, bbox_inches='tight')
    plt.show()

In [7]:
"""Key agreement performance: there are two important durations to keep track of
total duration is the time from handshake start to exiting DoTls13ServerHello
CPU duration is the time during which the CPU is doing crypto work, so it is the
total duration minus the time between "ClientHello sent" and "ServerHello done"
"""

summary = handshake_df.groupby(["kex"]).agg({
    "kex_cpu_dur": ["median", "std"],
    "kex_crypto_cpu_dur": ["median", "std"],
    "kex_dur": ["median", "std", "count"],
}).round(2).rename(
    columns={
        "kex_cpu_dur": "KEX CPU time",
        "kex_crypto_cpu_dur": "KEX crypto CPU time",
        "kex_dur": "KEX total time",
    }
).reset_index()
display(summary)

# plot_multiple_histograms(
#     {
#         kex: handshake_df.loc[handshake_df["kex"] == kex, "kex_cpu_dur"]
#         for kex in handshake_df["kex"].unique()
#     },
#     bins=list(range(0, 1_500_000, 5_000)),
#     title="Key exchange CPU time",
#     save="imgs/kex_cpu_dur.png",
# )
# plot_multiple_histograms(
#     {
#         kex: handshake_df.loc[handshake_df["kex"] == kex, "kex_crypto_cpu_dur"]
#         for kex in handshake_df["kex"].unique()
#     },
#     bins=list(range(0, 1_500_000, 5_000)),
#     title="Key exchange crypto time",
#     save="imgs/kex_crypto_cpu_dur.png",
# )
# plot_multiple_histograms(
#     {
#         kex: handshake_df.loc[handshake_df["kex"] == kex, "kex_dur"]
#         for kex in handshake_df["kex"].unique()
#     },
#     bins=list(range(0, 1_500_000, 5_000)),
#     title="Key exchange time",
#     save="imgs/kex_dur.png",
# )

         kex KEX CPU time         KEX crypto CPU time         KEX total time  \
                   median     std              median     std         median
0     hqc128    1322884.0   66.31           1314945.0   15.17      1342704.0
1     hqc192    4004725.0   98.97           3993143.0   20.47      4041491.0
2     hqc256    7314295.0  141.06           7296353.0   25.80      7381004.0
3  mlkem1024      42006.0  136.61             36457.0  140.17        51239.0
4   mlkem512      20034.0  169.75             15823.0   70.56        25336.5
5   mlkem768      28975.0  211.14             24260.0  127.33        34454.0
6  secp256r1     383796.0  147.12            381535.5  128.48       388897.0


         std count
0  133673.87  6908
1  193894.95  2538
2  106029.65  2305
3   12405.78  4278
4   15981.96  2364
5    8962.32  5597
6  100678.90  2334

In [8]:
# Authentication
summary = handshake_df.groupby(["auth"]).agg({
    "auth_crypto_dur": ["median", "std"],
    "auth_dur": ["median", "std", "count"],
}).sort_values(("auth_dur","median")).round(2).rename(
    columns={
        "auth_crypto_dur": "Auth crypto time",
        "auth_dur": "Auth time",
    }
).reset_index()
display(summary)

# plot_multiple_histograms(
#     {
#         auth: handshake_df.loc[handshake_df["auth"] == auth, "auth_crypto_dur"]
#         for auth in handshake_df["auth"].unique()
#     },
#     bins=list(range(0, 700_000, 1_000)),
#     title="Auth crypto time",
#     save="imgs/auth_crypto_dur.png"
# )

# plot_multiple_histograms(
#     {
#         auth: handshake_df.loc[handshake_df["auth"] == auth, "auth_dur"]
#         for auth in handshake_df["auth"].unique()
#     },
#     bins=list(range(0, 1_500_000, 3_000)),
#     title="Authentication time",
#     save="imgs/auth_time.png"
# )

handshake_df["hs_suite"] = handshake_df["kex"] + "," + handshake_df["auth"]
summary = handshake_df.groupby(["kex", "auth"]).agg({
    "hs_dur": ["median", "std", "count"],
}).sort_values(("hs_dur","median")).round(2).rename(
    columns={
        "hs_dur": "handshake latency",
    }
).reset_index()
display(summary)

# plot_multiple_histograms(
#     {
#         suite: handshake_df.loc[handshake_df["hs_suite"] == suite, "hs_dur"]
#         for suite in handshake_df["hs_suite"].unique()
#     },
#     bins=list(range(0, 3_000_000, 3_000)),
#     title="Handshake latency",
#     save="imgs/hs_time.png"
# )

                                   auth Auth crypto time            Auth time  \
                                                  median       std     median
0               rsa2048-rsa2048-rsa2048          17931.0     25.57    80590.0
1          falcon512-falcon512-mlkem512          14915.0     33.43   108105.0
2               mldsa44-mldsa44-mldsa44          23247.5     21.53   117040.5
3        falcon1024-falcon1024-mlkem768          17940.0     31.56   125706.0
4       falcon1024-falcon1024-mlkem1024          23647.0     30.51   134426.0
5              mldsa44-mldsa44-mlkem512          13328.0     29.75   140961.5
6              mldsa65-mldsa65-mlkem768          17898.0     30.95   193688.0
7              mldsa87-mldsa87-mlkem768          18429.0     33.03   252154.0
8             mldsa87-mldsa87-mlkem1024          24458.0     32.48   261422.0
9   sha256ecdsa-sha256ecdsa-sha256ecdsa         128629.0   1239.37   405919.0
10     sphincs128s-sphincs128s-mlkem512          14465.0     32.19   843983.0
11  sphincs128s-sphincs128s-sphincs128s         348916.0  13035.29  1140615.5
12     sphincs192s-sphincs192s-mlkem768          17086.0     28.78  1163876.5
13      sphincs192s-sphincs192s-mldsa65          39610.0     34.92  1168539.0
14       sphincs128s-sphincs128s-hqc128         663889.0     31.32  1516909.5
15      sphincs256s-sphincs256s-mldsa87          65494.0     21.26  1711873.0
16    sphincs256s-sphincs256s-mlkem1024          23892.0     31.47  1723529.0
17       sphincs192s-sphincs192s-hqc192        2003680.0     30.71  3158111.5
18       sphincs256s-sphincs256s-hqc256        3653333.0     29.28  5443263.0


          std count
0     7689.41  2234
1    24847.30  1071
2      314.73   104
3    11832.65  1310
4    18467.40  1530
5    18934.54   102
6    17396.98  1445
7    34066.46  1666
8    31782.50  1719
9     1273.67   100
10   55197.87  1087
11   15070.59  3568
12   32781.83  1176
13    1763.75  1236
14  131448.37  3340
15    2895.79  1209
16   97981.36  1029
17  158906.73  1302
18  189617.33  1096

          kex                                 auth handshake latency  \
                                                              median
0    mlkem512         falcon512-falcon512-mlkem512          157687.0
1    mlkem512              mldsa44-mldsa44-mldsa44          164019.5
2    mlkem768       falcon1024-falcon1024-mlkem768          183946.5
3    mlkem512             mldsa44-mldsa44-mlkem512          189151.5
4   mlkem1024      falcon1024-falcon1024-mlkem1024          210244.5
5    mlkem768             mldsa65-mldsa65-mlkem768          275167.0
6    mlkem768             mldsa87-mldsa87-mlkem768          326002.0
7   mlkem1024            mldsa87-mldsa87-mlkem1024          354981.0
8   secp256r1              rsa2048-rsa2048-rsa2048          486970.0
9   secp256r1  sha256ecdsa-sha256ecdsa-sha256ecdsa          810259.5
10   mlkem512     sphincs128s-sphincs128s-mlkem512          925493.0
11   mlkem768     sphincs192s-sphincs192s-mlkem768         1277371.5
12  mlkem1024    sphincs256s-sphincs256s-mlkem1024         1899104.0
13     hqc128  sphincs128s-sphincs128s-sphincs128s         2540080.0
14     hqc128       sphincs128s-sphincs128s-hqc128         2918399.0
15     hqc192      sphincs192s-sphincs192s-mldsa65         5299501.0
16     hqc192       sphincs192s-sphincs192s-hqc192         7304369.0
17     hqc256      sphincs256s-sphincs256s-mldsa87         9243921.0
18     hqc256       sphincs256s-sphincs256s-hqc256        12987320.5


          std count
0    37145.59  1071
1     7742.55   104
2    16618.27  1310
3    20774.16   102
4    30846.48  1530
5    29293.25  1445
6    35235.57  1666
7    35428.57  1719
8   103761.19  2234
9    21448.88   100
10   74438.44  1087
11   51458.02  1176
12  226068.66  1029
13  128924.41  3568
14  223598.25  3340
15  304464.20  1236
16  243299.18  1302
17   40152.74  1209
18  445509.98  1096