In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

handshake_df = pd.read_csv("./handshake.csv")
display(
    handshake_df.groupby(["kex", "auth"]).size(
    ).reset_index(name="count").sort_values(["kex", "auth"])
)

# only take the fastest 1000 runs based on handshake latecy
handshake_df = (
    handshake_df.groupby(["kex", "auth"], group_keys=False)
    .apply(lambda group: group.nsmallest(1000, 'hs_dur'))
)

            kex                                 auth  count
0        hqc128       sphincs128s-sphincs128s-hqc128   3340
1        hqc128  sphincs128s-sphincs128s-sphincs128s   3568
2        hqc192       sphincs192s-sphincs192s-hqc192   1302
3        hqc192      sphincs192s-sphincs192s-mldsa65   1236
4        hqc256       sphincs256s-sphincs256s-hqc256   1068
5        hqc256      sphincs256s-sphincs256s-mldsa87   1209
6     mlkem1024     falcon1024-falcon1024-falcon1024   1047
7     mlkem1024        falcon1024-falcon1024-mldsa87   1348
8     mlkem1024      falcon1024-falcon1024-mlkem1024   1530
9     mlkem1024              mldsa87-mldsa87-mldsa87   1346
10    mlkem1024            mldsa87-mldsa87-mlkem1024   1719
11    mlkem1024   sphincs256s-sphincs256s-falcon1024   1331
12    mlkem1024      sphincs256s-sphincs256s-mldsa87   1126
13    mlkem1024    sphincs256s-sphincs256s-mlkem1024   1029
14     mlkem512         falcon512-falcon512-mlkem512   1071
15     mlkem512              mldsa44-mldsa44-mldsa44    104
16     mlkem512             mldsa44-mldsa44-mlkem512    102
17     mlkem512             mldsa65-mldsa65-mlkem512   1409
18     mlkem512      sphincs128s-sphincs128s-mldsa44   1479
19     mlkem512     sphincs128s-sphincs128s-mlkem512   1087
20     mlkem768        falcon1024-falcon1024-mldsa65   1536
21     mlkem768       falcon1024-falcon1024-mlkem768   1310
22     mlkem768              mldsa65-mldsa65-mldsa65   1595
23     mlkem768             mldsa65-mldsa65-mlkem768   1445
24     mlkem768             mldsa87-mldsa87-mlkem768   1666
25     mlkem768      sphincs192s-sphincs192s-mldsa65   1078
26     mlkem768     sphincs192s-sphincs192s-mlkem768   1176
27  otmlkem1024              mldsa87-mldsa87-mldsa87   1453
28   otmlkem512              mldsa44-mldsa44-mldsa44   1197
29   otmlkem768              mldsa65-mldsa65-mldsa65   1525
30    secp256r1              rsa2048-rsa2048-rsa2048   2234
31    secp256r1  sha256ecdsa-sha256ecdsa-sha256ecdsa    100

/var/folders/r7/pnqk22j125731l_64c968zbc0000gn/T/ipykernel_91800/835523969.py:14: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda group: group.nsmallest(1000, 'hs_dur'))

In [2]:
def plot_multiple_histograms(data_dict, bins=10, alpha=0.6, title=None, 
                             density=True, save=None, figsize=(15, 6)):
    """
    Plots multiple histograms on the same figure for each label in the input dictionary.

    Parameters:
        data_dict (dict): A dictionary where keys are labels (str) and values are lists of integers.
        bins (int): Number of bins to use in the histograms.
        alpha (float): Transparency level for the histograms (0.0 to 1.0).
        title (str): Title of the plot.
    """
    plt.figure(figsize=figsize)

    for label, values in data_dict.items():
        weights = (np.ones_like(values) / len(values)) * 100
        plt.hist(values, bins=bins, alpha=alpha, label=label, weights=weights)

    if title:
        plt.title(title)
    plt.xlabel("Duration (microseconds)")
    plt.ylabel("Percentage" if density else "Count")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    if save:
        plt.savefig(save, dpi=1200, bbox_inches='tight')
    plt.show()

In [3]:
"""Key agreement performance: there are two important durations to keep track of
total duration is the time from handshake start to exiting DoTls13ServerHello
CPU duration is the time during which the CPU is doing crypto work, so it is the
total duration minus the time between "ClientHello sent" and "ServerHello done"
"""

summary = handshake_df.groupby(["kex"]).agg({
    "kex_cpu_dur": ["median", "std"],
    "kex_crypto_cpu_dur": ["median", "std"],
    "kex_dur": ["median", "std", "count"],
}).round(2).sort_values(
    ("kex_dur", "median")
).rename(
    columns={
        "kex_cpu_dur": "KEX CPU time",
        "kex_crypto_cpu_dur": "KEX crypto CPU time",
        "kex_dur": "KEX total time",
    }
).reset_index()
display(summary)

if 0:
    plot_multiple_histograms(
        {
            "ML-KEM-512": handshake_df.loc[
                handshake_df["kex"] == "mlkem512", "kex_dur"
            ],
            "OT-ML-KEM-512": handshake_df.loc[
                handshake_df["kex"] == "otmlkem512", "kex_dur"
            ],
        },
        bins=list(range(0, 100_000, 1_000)),
        save="imgs/mlkem512-cca-vs-1cca.png"
    )

    plot_multiple_histograms(
        {
            "ML-KEM-768": handshake_df.loc[
                handshake_df["kex"] == "mlkem768", "kex_dur"
            ],
            "OT-ML-KEM-768": handshake_df.loc[
                handshake_df["kex"] == "otmlkem768", "kex_dur"
            ],
        },
        bins=list(range(0, 100_000, 1_000)),
        save="imgs/mlkem768-cca-vs-1cca.png"
    )
    plot_multiple_histograms(
        {
            "ML-KEM-1024": handshake_df.loc[
                handshake_df["kex"] == "mlkem1024", "kex_dur"
            ],
            "OT-ML-KEM-1024": handshake_df.loc[
                handshake_df["kex"] == "otmlkem1024", "kex_dur"
            ],
        },
        bins=list(range(0, 100_000, 1_000)),
        save="imgs/mlkem1024-cca-vs-1cca.png"
    )

           kex KEX CPU time         KEX crypto CPU time          \
                     median     std              median     std
0   otmlkem512      14065.0   39.22             10356.0   32.69
1     mlkem512      20041.0  164.51             15845.0   93.27
2   otmlkem768      20071.0   57.84             15262.0   47.17
3     mlkem768      28985.0  217.70             24274.0  119.43
4  otmlkem1024      27879.0   68.68             22302.0   64.37
5    mlkem1024      41991.0  137.78             36455.0  134.64
6    secp256r1     383791.5  144.38            381534.5  125.85
7       hqc128    1322884.0   58.63           1314945.0   15.04
8       hqc192    4004725.0   95.34           3993142.0   20.39
9       hqc256    7314304.0  139.59           7296353.0   25.59

  KEX total time
          median       std count
0        20840.0   4206.79  1000
1        24794.5   9390.40  4206
2        26195.5   3441.57  1000
3        33967.5   5717.48  7000
4        36102.5   2453.64  1000
5        51070.5   5987.77  8000
6       388032.5   2854.89  1100
7      1341244.5   5498.32  2000
8      4040805.0   6251.72  2000
9      7380111.0  11151.01  2000

In [4]:
# Authentication
summary = handshake_df.groupby(["auth"]).agg({
    "auth_crypto_dur": ["median", "std"],
    "auth_dur": ["median", "std", "count"],
}).sort_values(("auth_dur","median")).round(2).rename(
    columns={
        "auth_crypto_dur": "Auth crypto time",
        "auth_dur": "Auth time",
    }
).reset_index()
display(summary)

handshake_df["hs_suite"] = handshake_df["kex"] + "," + handshake_df["auth"]
summary = handshake_df.groupby(["kex", "auth"]).agg({
    "hs_dur": ["median", "std", "count"],
}).sort_values(("hs_dur","median")).round(2).rename(
    columns={
        "hs_dur": "handshake latency",
    }
).reset_index()
display(summary)

                                   auth Auth crypto time           Auth time  \
                                                  median      std     median
0               rsa2048-rsa2048-rsa2048          17930.0    26.03    80593.0
1      falcon1024-falcon1024-falcon1024          12380.0    10.69    82915.0
2          falcon512-falcon512-mlkem512          14915.0    33.44   107118.5
3         falcon1024-falcon1024-mldsa65          39575.0    30.08   116527.0
4               mldsa44-mldsa44-mldsa44          23248.0    21.35   117080.5
5        falcon1024-falcon1024-mlkem768          17939.5    30.90   124804.5
6       falcon1024-falcon1024-mlkem1024          23645.0    30.02   133261.5
7              mldsa44-mldsa44-mlkem512          13328.0    29.75   140961.5
8         falcon1024-falcon1024-mldsa87          67465.0    35.45   152648.0
9               mldsa65-mldsa65-mldsa65          38417.0    20.57   176606.0
10             mldsa65-mldsa65-mlkem512          13608.0    31.50   180912.5
11             mldsa65-mldsa65-mlkem768          17898.0    31.36   190830.5
12             mldsa87-mldsa87-mlkem768          18430.0    32.95   249737.5
13            mldsa87-mldsa87-mlkem1024          24457.0    31.45   258661.5
14              mldsa87-mldsa87-mldsa87          65371.0    20.25   274107.5
15  sha256ecdsa-sha256ecdsa-sha256ecdsa         128629.0  1239.37   405919.0
16      sphincs128s-sphincs128s-mldsa44           6666.0     6.47   763353.0
17     sphincs128s-sphincs128s-mlkem512          14465.0    32.09   841305.0
18  sphincs128s-sphincs128s-sphincs128s         339141.5  7758.01  1130286.0
19     sphincs192s-sphincs192s-mlkem768          17086.0    28.74  1162462.5
20      sphincs192s-sphincs192s-mldsa65          39606.0    34.21  1168531.0
21       sphincs128s-sphincs128s-hqc128         663889.0    31.43  1480765.0
22   sphincs256s-sphincs256s-falcon1024          12728.0    11.59  1617799.0
23      sphincs256s-sphincs256s-mldsa87          65518.0    30.69  1711808.5
24    sphincs256s-sphincs256s-mlkem1024          23893.0    31.55  1723219.5
25       sphincs192s-sphincs192s-hqc192        2003681.0    30.27  3156085.0
26       sphincs256s-sphincs256s-hqc256        3653333.0    29.30  5442551.0


         std count
0     128.60  1000
1     497.63  1000
2   17081.24  1000
3     242.57  1000
4     473.17  1104
5    3175.23  1000
6    2427.82  1000
7   18934.54   102
8     514.94  1000
9     743.49  2000
10   7019.93  1000
11   9042.40  1000
12   3306.57  1000
13   3805.98  1000
14    745.21  2000
15   1273.67   100
16    412.39  1000
17  32294.14  1000
18   7723.88  1000
19  17567.99  1000
20    781.00  2000
21   8998.96  1000
22   1399.10  1000
23   1232.87  2000
24  17025.75  1000
25  14530.18  1000
26  11790.08  1000

            kex                                 auth handshake latency  \
                                                                median
0      mlkem512         falcon512-falcon512-mlkem512          155338.5
1     mlkem1024     falcon1024-falcon1024-falcon1024          157017.5
2    otmlkem512              mldsa44-mldsa44-mldsa44          161103.0
3      mlkem512              mldsa44-mldsa44-mldsa44          164019.5
4      mlkem768        falcon1024-falcon1024-mldsa65          175061.0
5      mlkem768       falcon1024-falcon1024-mlkem768          182072.0
6      mlkem512             mldsa44-mldsa44-mlkem512          189151.5
7     mlkem1024      falcon1024-falcon1024-mlkem1024          207286.5
8     mlkem1024        falcon1024-falcon1024-mldsa87          227285.5
9      mlkem512             mldsa65-mldsa65-mlkem512          234998.0
10   otmlkem768              mldsa65-mldsa65-mldsa65          235829.0
11     mlkem768              mldsa65-mldsa65-mldsa65          242668.5
12     mlkem768             mldsa65-mldsa65-mlkem768          265404.0
13     mlkem768             mldsa87-mldsa87-mlkem768          320479.5
14    mlkem1024            mldsa87-mldsa87-mlkem1024          346392.0
15  otmlkem1024              mldsa87-mldsa87-mldsa87          347023.5
16    mlkem1024              mldsa87-mldsa87-mldsa87          364684.0
17    secp256r1              rsa2048-rsa2048-rsa2048          484227.5
18    secp256r1  sha256ecdsa-sha256ecdsa-sha256ecdsa          810259.5
19     mlkem512      sphincs128s-sphincs128s-mldsa44          832089.0
20     mlkem512     sphincs128s-sphincs128s-mlkem512          920267.5
21     mlkem768     sphincs192s-sphincs192s-mlkem768         1273262.5
22     mlkem768      sphincs192s-sphincs192s-mldsa65         1284516.5
23    mlkem1024   sphincs256s-sphincs256s-falcon1024         1786865.0
24    mlkem1024      sphincs256s-sphincs256s-mldsa87         1889936.5
25    mlkem1024    sphincs256s-sphincs256s-mlkem1024         1898008.5
26       hqc128  sphincs128s-sphincs128s-sphincs128s         2523215.5
27       hqc128       sphincs128s-sphincs128s-hqc128         2882619.0
28       hqc192      sphincs192s-sphincs192s-mldsa65         5297305.5
29       hqc192       sphincs192s-sphincs192s-hqc192         7295234.5
30       hqc256      sphincs256s-sphincs256s-mldsa87         9239716.5
31       hqc256       sphincs256s-sphincs256s-hqc256        12984829.0


         std count
0   26770.55  1000
1    4851.80  1000
2    4288.22  1000
3    7742.55   104
4    1334.43  1000
5    3969.02  1000
6   20774.16   102
7    3046.61  1000
8    1479.05  1000
9    8730.33  1000
10   3634.70  1000
11   1552.12  1000
12  12889.28  1000
13   4347.51  1000
14   5358.21  1000
15   2673.04  1000
16   4219.48  1000
17    866.73  1000
18  21448.88   100
19   5538.95  1000
20  38396.82  1000
21  23054.63  1000
22  21283.48  1000
23  10369.33  1000
24  18320.45  1000
25  37830.85  1000
26   7040.76  1000
27  10790.87  1000
28   5829.67  1000
29  16437.96  1000
30  13664.06  1000
31  23780.34  1000